### ISSUE TITLE
type.constructFromObject is not a function

### ISSUE THREAD

**Issue by zombieleet** [textmagic/textmagic-rest-nodejs-v2#1]
I am unable to use the `getLists` method of textmagic, I don't know if this is the behavior of other methods, but this is the error message

```
node:4728) UnhandledPromiseRejectionWarning: TypeError: type.constructFromObject is not a function
    at Function.exports.convertToType (/root/wellnite-deployment/node_modules/textmagic-client/src/ApiClient.js:527:23)
    at /root/wellnite-deployment/node_modules/textmagic-client/src/ApiClient.js:532:28
    at Array.map (<anonymous>)
    at Function.exports.convertToType (/root/wellnite-deployment/node_modules/textmagic-client/src/ApiClient.js:531:23)
    at Function.exports.constructFromObject (/root/wellnite-deployment/node_modules/textmagic-client/src/model/GetListsPaginatedResponse.js:81:38)
    at Function.exports.convertToType (/root/wellnite-deployment/node_modules/textmagic-client/src/ApiClient.js:527:23)
    at exports.deserialize (/root/wellnite-deployment/node_modules/textmagic-client/src/ApiClient.js:350:20)
    at /root/wellnite-deployment/node_modules/textmagic-client/src/ApiClient.js:473:30
    at Request.callback (/root/wellnite-deployment/node_modules/textmagic-client/node_modules/superagent/lib/node/index.js:681:16)
    at /root/wellnite-deployment/node_modules/textmagic-client/node_modules/superagent/lib/node/index.js:891:18
(node:4728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**My Code**
```

const textMagicClient = require("textmagic-client");
const config          = require("../config.js");

const client          = textMagicClient.ApiClient.instance;
const auth            = client.authentications["BasicAuth"];

auth.username         = config.textMagicUserName;
auth.password         = config.textMagicApiKey;

class TextMagicService {
    constructor() {
        this.textMagic = new textMagicClient.TextMagicApi();
        console.log(this.textMagic);
    }
    createContact() {

    }
    sendMessage() {
    }

    async getList() {
        await this.textMagic.getLists();
    }
}

var s = new TextMagicService();

;( async () => {
    console.log(await s.getList());
})();
```

**Comment by imissyouso** [comment]
Hi @zombieleet, thank you for your feedback.
We've fixed this issue, please update `textmagic-client` to version `2.0.1029`:
```
npm install --save textmagic-client@2.0.1029
```
and try to run your code again.
